/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/home/udo/work/upp/src/lib/tcc"
#endif
#define TCC_VERSION "0.9.27"
#define UPP_VERSION "0.0.1"
